apiVersion: multicluster.odf.openshift.io/v1alpha1
kind: MirrorPeer
metadata:
  name: 'mirrorpeer-prod-a-prod-p'
  labels:
    cluster.open-cluster-management.io/backup: resource
spec:
  items:
  - clusterName: 'prod-a'
    storageClusterRef:
      name: ocs-storagecluster
      namespace: openshift-storage
  - clusterName: 'prod-p'
    storageClusterRef:
      name: ocs-storagecluster
      namespace: openshift-storage
  manageS3: true
  overlappingCIDR: false
  type: async