apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  annotations:
    cluster.open-cluster-management.io/submariner-broker-ns: production-broker
  generation: 1
  name: production
spec:
  clusterSelector:
    selectorType: ExclusiveClusterSetLabel