apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/vault-config-operator/

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: alpha
    target:
      kind: Subscription
  - patch: |-
      - op: replace
        path: /spec/config/env/0/value
        value: https://vault.non-prod.example.com:8200
    target:
      kind: Subscription 