apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: vm-dr-placement-drpc
spec:
  drPolicyRef:
    apiVersion: ramendr.openshift.io/v1alpha1
    kind: DRPolicy
    name: prod-a-prod-p-10
  placementRef:
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: Placement
    name: vm-dr-placement
    namespace: openshift-gitops
  preferredCluster: prod-a
  pvcSelector:
    matchLabels:
      app.kubernetes.io/component: storage

