apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  annotations:
    drplacementcontrol.ramendr.openshift.io/app-namespace: vm-dr
    drplacementcontrol.ramendr.openshift.io/last-app-deployment-cluster: prod-a
  name: vm-dr-placement-drpc
  labels:
    cluster.open-cluster-management.io/backup: ramen
spec:
  drPolicyRef:
    apiVersion: ramendr.openshift.io/v1alpha1
    kind: DRPolicy
    name: prod-a-prod-p-10
  placementRef:
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: Placement
    name: vm-dr-placement
    namespace: openshift-gitops
  preferredCluster: prod-a
  pvcSelector:
    matchLabels:
      appname: busybox

