applications:

  acm-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: open-cluster-management
    source:
      path: components/acm-operator 

  acm-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: open-cluster-management
    source:
      path: components/acm-configuration

  openshift-config:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    source:
      path: clusters/hub/overlays/openshift-config 

  odf-multicluster-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    source:
      path: components/odf-multicluster-operator

  acm-odf-dr:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    source:
      path: components/acm-odf-dr                                  


# clusters

  prod-a:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: prod-a
    source:
      path: clusters/hub/overlays/prod-a     
    extraFields: |
      ignoreDifferences:
        - group: ''
          jsonPointers:
            - /data
          kind: Secret
        - group: 'hive.openshift.io'
          jsonPointers:
            - /spec/installed
          kind: ClusterDeployment
        - group: 'redhatcop.redhat.io'
          jsonPointers:
            - /spec/kubernetesHost
          kind: KubernetesAuthEngineConfig 

  prod-p:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: prod-p
    source:
      path: clusters/hub/overlays/prod-p     
    extraFields: |
      ignoreDifferences:
        - group: ''
          jsonPointers:
            - /data
          kind: Secret
        - group: 'hive.openshift.io'
          jsonPointers:
            - /spec/installed
          kind: ClusterDeployment
        - group: 'redhatcop.redhat.io'
          jsonPointers:
            - /spec/kubernetesHost
          kind: KubernetesAuthEngineConfig           
                          