apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,ServerSideApply=true
  name: cluster
spec:
  plugins:
  - logging-view-plugin
  - monitoring-plugin
  - odf-console
