apiVersion: v1
kind: Namespace
metadata:
  name: prod-a
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,ServerSideApply=true
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops 